/* Generated By:JJTree: Do not edit this line. AstCast.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class AstCast extends SimpleNode
{
    /**
     * Types which accept a size: CHAR(n), VARCHAR(n), DECIMAL(n[, scale])
     * and pgvector types VECTOR(dimensions), HALFVEC(dimensions), SPARSEVEC(dimensions), BIT(n).
     */
    private static final List<String> SIZED_TYPES = Collections.unmodifiableList(Arrays.asList(
            "CHAR", "VARCHAR", "DECIMAL", "VECTOR", "HALFVEC", "SPARSEVEC", "BIT"));

    private String dataType;
    private int size = -1;
    private int scale = -1;

    public AstCast(int id)
    {
        super(id);
        this.nodePrefix = "CAST(";
        this.nodeSuffix = ")";
    }

    public AstCast(SimpleNode child, String dataType)
    {
        this(SqlParserTreeConstants.JJTCAST);
        setDataType(dataType);
        addChild(child);
    }

    public AstCast(SimpleNode child, String dataType, int size)
    {
        this(SqlParserTreeConstants.JJTCAST);
        setDataType(dataType);
        setSize(size);
        addChild(child);
    }

    @Override
    public void jjtClose()
    {
        // Postfix cast (expr::type) node is opened at the "::" token, while it actually starts with the cast expression
        if (firstToken != null && firstToken.kind == SqlParserConstants.DOUBLE_COLON && jjtGetNumChildren() == 1)
        {
            SimpleNode child = child(0);
            firstToken = child.jjtGetFirstToken();
            specialPrefix = child.getSpecialPrefix();
            child.specialPrefix = null;
        }
    }

    public void setDataType(String dataType)
    {
        this.dataType = dataType;
        this.nodeSuffix = "AS " + dataType + ")";
    }

    @Override
    public String getNodeSuffix()
    {
        if (dataType == null)
            return ")";
        if (size < 0)
            return "AS " + dataType + ")";
        if (scale < 0)
            return "AS " + dataType + "(" + size + "))";
        return "AS " + dataType + "(" + size + ", " + scale + "))";
    }

    public String getDataType()
    {
        return dataType;
    }

    public int getSize()
    {
        return size;
    }

    public void setSize(int size)
    {
        if (size < 0)
            size = -1;
        if (size != -1 && !SIZED_TYPES.contains(String.valueOf(dataType).toUpperCase()))
            throw new IllegalArgumentException("Can specify cast size for " + String.join(", ", SIZED_TYPES)
                    + " types only");
        this.size = size;
    }

    public int getScale()
    {
        return scale;
    }

    public void setScale(int scale)
    {
        if (!"DECIMAL".equalsIgnoreCase(dataType))
            throw new IllegalArgumentException("Can specify cast scale for DECIMAL type only");
        this.scale = scale;
    }
}
/* JavaCC - OriginalChecksum=44964fcff6433fd51f23446299bdf8f5 (do not edit this line) */
